package com.Nhom5.UI2;

import com.Nhom5.DAO.DegreeDAO;
import com.Nhom5.DAO.DepartmentDAO;
import com.Nhom5.DAO.DutyDAO;
import com.Nhom5.DAO.EmloyeeDAO;
import com.Nhom5.Entity.Degree;
import com.Nhom5.Entity.Department;
import com.Nhom5.Entity.Duty;
import com.Nhom5.Entity.User;
import com.Nhom5.Helper.Auth;
import com.Nhom5.Helper.MsgBox;
import com.Nhom5.Helper.XImage;
import com.Nhom5.datechooser.EventDateChooser;
import com.Nhom5.datechooser.SelectedAction;
import com.Nhom5.datechooser.SelectedDate;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hvn45
 */
public class PnEmployee extends javax.swing.JPanel {

    User u;
    int checklap = 0;
    ArrayList<com.Nhom5.Entity.Employee> listStaff = new ArrayList<>();
    EmloyeeDAO dao = new EmloyeeDAO();
    int row = -1;
    final DefaultComboBoxModel department = new DefaultComboBoxModel();
    final DefaultComboBoxModel duty = new DefaultComboBoxModel();
    final DefaultComboBoxModel degree = new DefaultComboBoxModel();
    JFileChooser fileChooser = new JFileChooser("img");

    public PnEmployee() {
        initComponents();
        table();
        checkLimitDate();
        fillTable();
        fillCbbDepartment();
        fillCbbDuty();
        fillCbbDegree();
    }

    public PnEmployee(User entity) {
        initComponents();
        table();
        checkLimitDate();
        this.u = entity;
        setInforUser();
        if (this.u.getRole() == 0) {
            fillTable();
        } else {
            fillTable_1();
        }
        fillCbbDepartment();
        fillCbbDuty();
        fillCbbDegree();
        checkRole();
    }

    // Table
    public void table() {
        setBackground(new Color(255, 255, 255));
        tbl.getTableHeader().setFont(new Font("Seoge UI", Font.BOLD, 16));
        tbl.getTableHeader().setOpaque(false);
        tbl.getTableHeader().setBackground(new Color(236, 56, 188));
        tbl.getTableHeader().setForeground(new Color(255, 255, 255));
        tbl.setRowHeight(24);
        tbl.setSelectionBackground(new Color(84, 179, 237));
        tbl.setSelectionForeground(new Color(255, 255, 255));
    }

    // Set infor user
    public void setInforUser() {
        lbl_NameOfUser.setText(u.getName());
        lbl_DutyOfUser.setText(u.getDuty());
        lbl_Avatar.setIcon(XImage.read(u.getImg()));

    }

    public void checkRole() {
        if (this.u.getRole() == 1) {
            btn_Add.setEnabled(false);
            btn_Delete.setEnabled(false);
            btn_First.setEnabled(false);
            btn_Last.setEnabled(false);
            btn_Next.setEnabled(false);
            btn_Prev.setEnabled(false);
            btn_Update.setEnabled(false);
        }
    }

    public boolean checkRemoveYourself() {
        if (this.u.getId_Emp() == Integer.parseInt(txt_Id.getText())) {
            MsgBox.alert(this, "Bạn không thể xoá chính mình!!");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // fill data from database to table
    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        listStaff.clear();
        try {
            List<com.Nhom5.Entity.Employee> list = dao.selectAll(); // Đọc dữ liệu từ CSDL
            for (com.Nhom5.Entity.Employee e : list) {
                Object[] data = {
                    e.getIdEmployee(),
                    e.getNameEmployee(),
                    e.isGender() ? "Nam" : "Nữ",
                    e.getBirthday(),
                    e.getPhoneNumber(),
                    e.getCityzenIdentyCard(),
                    e.getAddress(),
                    e.getImg(),
                    e.getNameDepartment(),
                    e.getNameDuty(),
                    e.getNameDegree(),
                    e.getSalaryBasic(),};
                listStaff.add(e);
                model.addRow(data);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    public void fillTable_1() {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        listStaff.clear();
        try {
            com.Nhom5.Entity.Employee e = dao.selectById(String.valueOf(this.u.getId_Emp())); // Đọc dữ liệu từ CSDL

            Object[] data = {
                e.getIdEmployee(),
                e.getNameEmployee(),
                e.isGender() ? "Nam" : "Nữ",
                e.getBirthday(),
                e.getPhoneNumber(),
                e.getCityzenIdentyCard(),
                e.getAddress(),
                e.getImg(),
                e.getNameDepartment(),
                e.getNameDuty(),
                e.getNameDegree(),
                e.getSalaryBasic(),};
            listStaff.add(e);
            model.addRow(data);

        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    public void edit() {
        String idEmployee = (String) tbl.getValueAt(this.row, 0);
        com.Nhom5.Entity.Employee e = dao.selectById(idEmployee);
        this.setForm(e);
//        this.updateStatus();
    }

    public void setForm(com.Nhom5.Entity.Employee entity) {
        txt_Name.setText(entity.getNameEmployee());
        txt_Birthday.setText(entity.getBirthday());
        txt_CZC.setText(entity.getCityzenIdentyCard());
        rdo_Male.setSelected(entity.isGender());
        rdo_Male.setSelected(!entity.isGender());
        txt_Id.setText(entity.getIdEmployee());
        txt_PhoneNumber.setText(entity.getPhoneNumber());
        txt_Address.setText(entity.getAddress());
        cbb_Department.setSelectedItem(entity.getNameDepartment());
        cbb_Degree.setSelectedItem(entity.getNameDegree());
        cbb_Duty.setSelectedItem(entity.getNameDuty());
        txt_SalaryBasic.setText(entity.getSalaryBasic());
        lbl_Img.setToolTipText(entity.getImg());
        if (entity.getImg() != null) {
            lbl_Img.setIcon(XImage.read(entity.getImg()));
        }
//        txtdiaChi.setText(nv.getDiaChi());
        if (entity.isGender()) {
            rdo_Male.setSelected(true);
        } else {
            rdo_Famale.setSelected(true);
        }

    }

//    public void updateStatus() {
//        boolean edit = (this.row >= 0);
//        boolean first = (this.row == 0);
//        boolean last = (this.row == tblnhanVien.getRowCount() - 1);
////        Trạng thái form
//        btnThem.setEnabled(edit);
//        btnSua.setEnabled(edit);
//        btnXoa.setEnabled(edit);
//// Trạng thái điều hướng
//        btnFirst.setEnabled(edit && !first);
//        btnPrev.setEnabled(edit && !first);
//        btnNext.setEnabled(edit && !last);
//        btnLast.setEnabled(edit && !last);
//        txtOFF();
//    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.Nhom5.datechooser.DateChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pn_Table = new com.Nhom5.Components.pnGradientColor();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        pn_infoEmployee = new javax.swing.JPanel();
        lbl_Img = new com.Nhom5.Swing.BoderRadius();
        rdo_Famale = new javax.swing.JRadioButton();
        rdo_Male = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_Birthday = new javax.swing.JTextField();
        txt_PhoneNumber = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_CZC = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        lbl_VND = new javax.swing.JLabel();
        txt_SalaryBasic = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cbb_Degree = new javax.swing.JComboBox<>();
        cbb_Department = new javax.swing.JComboBox<>();
        cbb_Duty = new javax.swing.JComboBox<>();
        btn_Delete = new javax.swing.JLabel();
        btn_Add = new javax.swing.JLabel();
        btn_Clear = new javax.swing.JLabel();
        btn_Update = new javax.swing.JLabel();
        btn_Last = new javax.swing.JLabel();
        btn_First = new javax.swing.JLabel();
        btn_Prev = new javax.swing.JLabel();
        btn_Next = new javax.swing.JLabel();
        txt_Address = new javax.swing.JTextField();
        txt_Id = new javax.swing.JTextField();
        txt_Name = new javax.swing.JTextField();
        pn_Contact = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_NameOfUser = new javax.swing.JLabel();
        lbl_DutyOfUser = new javax.swing.JLabel();
        lbl_Avatar = new com.Nhom5.Swing.BoderRadius();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pn_Find = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        dateChooser1.setForeground(new java.awt.Color(236, 56, 188));
        dateChooser1.setTextRefernce(txt_Birthday);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ và tên", "Giới tính", "Ngày sinh", "Số điện thoại", "CCCD", "Địa chỉ", "Ảnh", "Phòng ban", "Chức vụ", "Trình độ", "Lương cơ bản"
            }
        ));
        tbl.setFocusable(false);
        tbl.setGridColor(new java.awt.Color(236, 56, 188));
        tbl.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl.setRowHeight(25);
        tbl.setSelectionBackground(new java.awt.Color(84, 179, 237));
        tbl.getTableHeader().setReorderingAllowed(false);
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout pn_TableLayout = new javax.swing.GroupLayout(pn_Table);
        pn_Table.setLayout(pn_TableLayout);
        pn_TableLayout.setHorizontalGroup(
            pn_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TableLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_TableLayout.setVerticalGroup(
            pn_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TableLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(pn_Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 1610, 560));

        pn_infoEmployee.setBackground(new java.awt.Color(255, 255, 255));
        pn_infoEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn_infoEmployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Img.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Images/user.png"))); // NOI18N
        lbl_Img.setRoundBottomLeft(130);
        lbl_Img.setRoundBottomRight(130);
        lbl_Img.setRoundTopLeft(130);
        lbl_Img.setRoundTopRight(130);
        lbl_Img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ImgMouseClicked(evt);
            }
        });
        pn_infoEmployee.add(lbl_Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 130, 130));

        rdo_Famale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdo_Famale);
        rdo_Famale.setText("Nữ");
        rdo_Famale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_FamaleActionPerformed(evt);
            }
        });
        pn_infoEmployee.add(rdo_Famale, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        rdo_Male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdo_Male);
        rdo_Male.setText("Nam");
        rdo_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_MaleActionPerformed(evt);
            }
        });
        pn_infoEmployee.add(rdo_Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        pn_infoEmployee.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 203, 2, 18));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel18.setText("Mã nhân viên:");
        pn_infoEmployee.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        txt_Birthday.setEditable(false);
        txt_Birthday.setBackground(new java.awt.Color(255, 255, 255));
        txt_Birthday.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        txt_Birthday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Birthday.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(84, 179, 237)));
        txt_Birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BirthdayActionPerformed(evt);
            }
        });
        pn_infoEmployee.add(txt_Birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 174, 100, 19));

        txt_PhoneNumber.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_PhoneNumber.setForeground(new java.awt.Color(236, 56, 188));
        txt_PhoneNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_PhoneNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(84, 179, 237)));
        txt_PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PhoneNumberActionPerformed(evt);
            }
        });
        pn_infoEmployee.add(txt_PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 130, 19));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel19.setText("Số điện thoại:");
        pn_infoEmployee.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        txt_CZC.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_CZC.setForeground(new java.awt.Color(236, 56, 188));
        txt_CZC.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_CZC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(84, 179, 237)));
        txt_CZC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CZCActionPerformed(evt);
            }
        });
        pn_infoEmployee.add(txt_CZC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 130, 19));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel20.setText("Số CCCD:");
        pn_infoEmployee.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        lbl_VND.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        lbl_VND.setText("VNĐ");
        lbl_VND.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(84, 179, 237)));
        pn_infoEmployee.add(lbl_VND, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 170, -1, -1));

        txt_SalaryBasic.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_SalaryBasic.setForeground(new java.awt.Color(236, 56, 188));
        txt_SalaryBasic.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_SalaryBasic.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(84, 179, 237)));
        txt_SalaryBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SalaryBasicActionPerformed(evt);
            }
        });
        pn_infoEmployee.add(txt_SalaryBasic, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 170, 100, 19));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel21.setText("Địa chỉ :");
        pn_infoEmployee.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel22.setText("Phòng ban:");
        pn_infoEmployee.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 50, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel23.setText("Chức vụ:");
        pn_infoEmployee.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 90, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel24.setText("Trình độ:");
        pn_infoEmployee.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 130, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel25.setText("Lương cơ bản:");
        pn_infoEmployee.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 170, -1, -1));

        cbb_Degree.setBackground(new java.awt.Color(253, 239, 249));
        cbb_Degree.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        cbb_Degree.setMaximumRowCount(20);
        cbb_Degree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_Degree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(144, 224, 239)));
        cbb_Degree.setName(""); // NOI18N
        cbb_Degree.setOpaque(false);
        pn_infoEmployee.add(cbb_Degree, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 130, 22));

        cbb_Department.setBackground(new java.awt.Color(253, 239, 249));
        cbb_Department.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        cbb_Department.setMaximumRowCount(20);
        cbb_Department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_Department.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(144, 224, 239)));
        cbb_Department.setName(""); // NOI18N
        cbb_Department.setOpaque(false);
        pn_infoEmployee.add(cbb_Department, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 130, 22));

        cbb_Duty.setBackground(new java.awt.Color(253, 239, 249));
        cbb_Duty.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        cbb_Duty.setMaximumRowCount(20);
        cbb_Duty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_Duty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(144, 224, 239)));
        cbb_Duty.setName(""); // NOI18N
        cbb_Duty.setOpaque(false);
        pn_infoEmployee.add(cbb_Duty, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 130, 22));

        btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Delete.png"))); // NOI18N
        btn_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DeleteMouseExited(evt);
            }
        });
        pn_infoEmployee.add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 20, 169, 44));

        btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Add.png"))); // NOI18N
        btn_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AddMouseExited(evt);
            }
        });
        pn_infoEmployee.add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, 169, 44));

        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Clear.png"))); // NOI18N
        btn_Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ClearMouseExited(evt);
            }
        });
        pn_infoEmployee.add(btn_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 80, 169, 44));

        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Update.png"))); // NOI18N
        btn_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_UpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_UpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_UpdateMouseExited(evt);
            }
        });
        pn_infoEmployee.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 80, 169, 44));

        btn_Last.setBackground(new java.awt.Color(255, 255, 255));
        btn_Last.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Last.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Last.png"))); // NOI18N
        btn_Last.setToolTipText("");
        btn_Last.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LastMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LastMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LastMouseExited(evt);
            }
        });
        pn_infoEmployee.add(btn_Last, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 150, 74, 49));

        btn_First.setBackground(new java.awt.Color(255, 255, 255));
        btn_First.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_First.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_First.png"))); // NOI18N
        btn_First.setToolTipText("");
        btn_First.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_FirstMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_FirstMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_FirstMouseExited(evt);
            }
        });
        pn_infoEmployee.add(btn_First, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 150, 74, 49));

        btn_Prev.setBackground(new java.awt.Color(255, 255, 255));
        btn_Prev.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Prev.png"))); // NOI18N
        btn_Prev.setToolTipText("");
        btn_Prev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PrevMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_PrevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_PrevMouseExited(evt);
            }
        });
        pn_infoEmployee.add(btn_Prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 150, 74, 49));

        btn_Next.setBackground(new java.awt.Color(255, 255, 255));
        btn_Next.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Next.png"))); // NOI18N
        btn_Next.setToolTipText("");
        btn_Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_NextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_NextMouseExited(evt);
            }
        });
        pn_infoEmployee.add(btn_Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 150, 74, 49));

        txt_Address.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_Address.setForeground(new java.awt.Color(236, 56, 188));
        txt_Address.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_Address.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(84, 179, 237)));
        txt_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AddressActionPerformed(evt);
            }
        });
        pn_infoEmployee.add(txt_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 130, 19));

        txt_Id.setEditable(false);
        txt_Id.setBackground(new java.awt.Color(255, 255, 255));
        txt_Id.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_Id.setForeground(new java.awt.Color(236, 56, 188));
        txt_Id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_Id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(84, 179, 237)));
        txt_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdActionPerformed(evt);
            }
        });
        pn_infoEmployee.add(txt_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 130, 19));

        txt_Name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Name.setText("Họ và tên");
        txt_Name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(84, 179, 237)));
        txt_Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_NameMouseClicked(evt);
            }
        });
        txt_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NameActionPerformed(evt);
            }
        });
        pn_infoEmployee.add(txt_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 147, 130, 19));

        add(pn_infoEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 1610, 230));

        pn_Contact.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/twitter.png"))); // NOI18N

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/youtube32.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/facebook.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/internet.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/instagram.png"))); // NOI18N

        javax.swing.GroupLayout pn_ContactLayout = new javax.swing.GroupLayout(pn_Contact);
        pn_Contact.setLayout(pn_ContactLayout);
        pn_ContactLayout.setHorizontalGroup(
            pn_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_ContactLayout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_ContactLayout.setVerticalGroup(
            pn_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_ContactLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pn_ContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(pn_Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 980, 240, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_NameOfUser.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_NameOfUser.setForeground(new java.awt.Color(236, 56, 188));
        lbl_NameOfUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_NameOfUser.setText("Họ tên");
        jPanel3.add(lbl_NameOfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1262, 49, 139, -1));

        lbl_DutyOfUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_DutyOfUser.setForeground(new java.awt.Color(84, 179, 237));
        lbl_DutyOfUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_DutyOfUser.setText("Chức vụ");
        jPanel3.add(lbl_DutyOfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1262, 78, 139, -1));

        lbl_Avatar.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Images/user.png"))); // NOI18N
        lbl_Avatar.setRoundBottomLeft(130);
        lbl_Avatar.setRoundBottomRight(130);
        lbl_Avatar.setRoundTopLeft(130);
        lbl_Avatar.setRoundTopRight(130);
        jPanel3.add(lbl_Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1419, 13, 130, 130));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1256, 49, -1, -1));

        jLabel6.setFont(new java.awt.Font("Source Sans Pro Black", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Quản lý Nhân viên");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 55, -1, -1));

        pn_Find.setBackground(new java.awt.Color(255, 255, 255));
        pn_Find.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn_Find.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/search.png"))); // NOI18N
        pn_Find.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 32, 32));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("Tìm kiếm...");
        pn_Find.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 380, 41));

        jPanel3.add(pn_Find, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 1580, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_FamaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_FamaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_FamaleActionPerformed

    private void rdo_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_MaleActionPerformed

    private void txt_BirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BirthdayActionPerformed

    private void txt_PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PhoneNumberActionPerformed

    private void txt_CZCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CZCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CZCActionPerformed

    private void txt_SalaryBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SalaryBasicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SalaryBasicActionPerformed

    private void btn_DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DeleteMouseEntered
        btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_HoverDelete.png"))); // NOI18N
    }//GEN-LAST:event_btn_DeleteMouseEntered

    private void btn_DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DeleteMouseExited
        btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Delete.png"))); // NOI18N
    }//GEN-LAST:event_btn_DeleteMouseExited

    private void btn_AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseEntered
        btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_HoverAdd.png"))); // NOI18N
    }//GEN-LAST:event_btn_AddMouseEntered

    private void btn_AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseExited
        btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Add.png"))); // NOI18N
    }//GEN-LAST:event_btn_AddMouseExited

    private void btn_ClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ClearMouseEntered
        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_HoverClear.png"))); // NOI18N
    }//GEN-LAST:event_btn_ClearMouseEntered

    private void btn_ClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ClearMouseExited
        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Clear.png"))); // NOI18N
    }//GEN-LAST:event_btn_ClearMouseExited

    private void btn_UpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateMouseEntered
        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_HoverUpdate.png"))); // NOI18N
    }//GEN-LAST:event_btn_UpdateMouseEntered

    private void btn_UpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateMouseExited
        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Update.png"))); // NOI18N
    }//GEN-LAST:event_btn_UpdateMouseExited

    private void btn_LastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LastMouseEntered
        btn_Last.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_HoverLast.png"))); // NOI18N
    }//GEN-LAST:event_btn_LastMouseEntered

    private void btn_LastMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LastMouseExited
        btn_Last.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Last.png"))); // NOI18N
    }//GEN-LAST:event_btn_LastMouseExited

    private void btn_FirstMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FirstMouseEntered
        btn_First.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_HoverFirst.png"))); // NOI18N
    }//GEN-LAST:event_btn_FirstMouseEntered

    private void btn_FirstMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FirstMouseExited
        btn_First.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_First.png"))); // NOI18N
    }//GEN-LAST:event_btn_FirstMouseExited

    private void btn_PrevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrevMouseEntered
        btn_Prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_HoverPrev.png"))); // NOI18N
    }//GEN-LAST:event_btn_PrevMouseEntered

    private void btn_PrevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrevMouseExited
        btn_Prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Prev.png"))); // NOI18N
    }//GEN-LAST:event_btn_PrevMouseExited

    private void btn_NextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NextMouseEntered
        btn_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_HoverNext.png"))); // NOI18N
    }//GEN-LAST:event_btn_NextMouseEntered

    private void btn_NextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NextMouseExited
        btn_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Icons/btn_Next.png"))); // NOI18N
    }//GEN-LAST:event_btn_NextMouseExited

    private void txt_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AddressActionPerformed

    private void txt_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdActionPerformed

    private void txt_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameActionPerformed

    }//GEN-LAST:event_txt_NameActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        if (evt.getClickCount() == 1) {
            this.row = tbl.getSelectedRow();
            this.edit();
        }

    }//GEN-LAST:event_tblMouseClicked

    private void btn_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseClicked
        if (checkInputData() == true) {
            insert();
        }
    }//GEN-LAST:event_btn_AddMouseClicked

    private void lbl_ImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ImgMouseClicked
        if (evt.getClickCount() == 1) {
            selectImage();
        }
    }//GEN-LAST:event_lbl_ImgMouseClicked

    public void first() {
        this.row = 0;
        tbl.setRowSelectionInterval(row, row);
        this.edit();

    }

    public void prev() {
        if (this.row > 0) {
            this.row--;
            tbl.setRowSelectionInterval(row, row);
            this.edit();
        }
    }

    public void next() {
        if (this.row < tbl.getRowCount() - 1) {
            this.row++;
            tbl.setRowSelectionInterval(row, row);
            this.edit();
        }
    }

    public void last() {
        this.row = tbl.getRowCount() - 1;
        tbl.setRowSelectionInterval(row, row);
        this.edit();
    }

    private void btn_ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ClearMouseClicked
        clearForm();
    }//GEN-LAST:event_btn_ClearMouseClicked

    private void txt_NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NameMouseClicked
        if (evt.getClickCount() == 2) {
            txt_Name.setText("");
            txt_Name.requestFocus();
        }
    }//GEN-LAST:event_txt_NameMouseClicked

    private void btn_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DeleteMouseClicked
        if (tbl.getSelectedRow() == -1) {
            MsgBox.alert(this, "Bạn chưa chọn nhân sự muốn xoá");
        } else {
            if (checkRemoveYourself() == true) {
                delete();
            }
        }
    }//GEN-LAST:event_btn_DeleteMouseClicked

    private void btn_FirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_FirstMouseClicked
        first();
    }//GEN-LAST:event_btn_FirstMouseClicked

    private void btn_PrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrevMouseClicked
        prev();
    }//GEN-LAST:event_btn_PrevMouseClicked

    private void btn_NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NextMouseClicked
        next();
    }//GEN-LAST:event_btn_NextMouseClicked

    private void btn_LastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LastMouseClicked
        last();
    }//GEN-LAST:event_btn_LastMouseClicked

    private void btn_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateMouseClicked
        update();
    }//GEN-LAST:event_btn_UpdateMouseClicked

    public void delete() {
        String id = txt_Id.getText();

        if (MsgBox.confirm(this, "Bạn thực sự muốn xóa nhân sự này?")) {
            try {
                dao.delete(id);
                this.fillTable();
                this.clearForm();
                MsgBox.alert(this, "Xóa thành công");
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa thất bại");
            }
        }
    }

    public void update() {
        if (checkInputData() == true) {
            com.Nhom5.Entity.Employee emp = getForm();
            try {
                dao.update(emp);
                this.fillTable();
                clearForm();
                MsgBox.alert(this, "Cập nhật thành công");
            } catch (Exception e) {
                MsgBox.alert(this, "Cập nhật thất bại");

            }
        }

    }

    public void insert() {
        dao.insert(getForm());
        fillTable();
        clearForm();
        MsgBox.alert(this, "Thêm mới thành công");
    }

    public com.Nhom5.Entity.Employee getForm() {
        com.Nhom5.Entity.Employee e = new com.Nhom5.Entity.Employee();
        e.setIdEmployee(txt_Id.getText());
        e.setNameEmployee(txt_Name.getText());
        e.setBirthday(txt_Birthday.getText());
        e.setPhoneNumber(txt_PhoneNumber.getText());
        e.setCityzenIdentyCard(txt_CZC.getText());
        e.setAddress(txt_Address.getText());
        e.setImg(lbl_Img.getToolTipText());
        e.setIdDepartment(nameCbbToId(0, cbb_Department.getSelectedItem().toString()));
        e.setIdDuty(nameCbbToId(1, cbb_Duty.getSelectedItem().toString()));
        e.setIdDegree(nameCbbToId(2, cbb_Degree.getSelectedItem().toString()));
        e.setSalaryBasic(txt_SalaryBasic.getText());
        if (rdo_Male.isSelected()) {
            e.setGender(true);
        } else if (rdo_Famale.isSelected()){
            e.setGender(false);
        }
        return e;
    }

    public int nameCbbToId(int checkCbb, String name) {
        if (checkCbb == 0) {//Department
            DepartmentDAO dDAO = new DepartmentDAO();
            Department d = new Department();
            d = dDAO.selectById(name);
            return d.getIdDepartment();
        } else if (checkCbb == 1) {//Duty
            DutyDAO dDAO = new DutyDAO();
            Duty d = new Duty();
            d = dDAO.selectById(name);
            return d.getIdDuty();
        }
        if (checkCbb == 2) {//Degree
            DegreeDAO dDAO = new DegreeDAO();
            Degree d = new Degree();
            d = dDAO.selectById(name);
            return d.getIdDegree();
        }
        return 0;
    }
//    public String DateToString_ddMMyyyy(Date date){
//        String[] s = String.valueOf(date).split("-");
//        String x = "";
//        x = s[2]+"-"+s[1]+"-"+s[0];
//        return x;
//    }
//    public Date StringTo_yyyyMMdd(String string){
//        String[] s = string.split("-");
//        String x = "";
//        x = s[2]+"-"+s[1]+"-"+s[0];
//        Date date = null;
//        try {
//            date = new SimpleDateFormat("dd-MM-yyyy").parse(x);
//        } catch (ParseException ex) {
//            Logger.getLogger(PnEmployee.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        return date;
//    }

    public boolean checkInputData() {
        if (txt_Name.getText().equals("") == true) {
            MsgBox.alert(this, "Dữ liệu đầu vào không hợp lệ");
            return false;
        }
        if (txt_Birthday.getText().equals("") == true) {
            MsgBox.alert(this, "Dữ liệu đầu vào không hợp lệ");
            return false;
        }
        if (txt_CZC.getText().equals("") == true) {
            MsgBox.alert(this, "Dữ liệu đầu vào không hợp lệ");
            return false;
        }
        if (txt_CZC.getText().equals("") == true) {
            MsgBox.alert(this, "Dữ liệu đầu vào không hợp lệ");
            return false;
        }
        if (txt_PhoneNumber.getText().equals("") == true) {
            MsgBox.alert(this, "Dữ liệu đầu vào không hợp lệ");
            return false;
        }
        if (txt_SalaryBasic.getText().equals("") == true) {
            MsgBox.alert(this, "Dữ liệu đầu vào không hợp lệ");
            return false;
        } else {
            try {
                int a = Integer.parseInt(txt_SalaryBasic.getText());
            } catch (Exception e) {
                MsgBox.alert(this, "Không nhập ký tự cho lương cơ bản");
                return false;
            }
        }

        if (!rdo_Famale.isSelected() && !rdo_Male.isSelected()) {
            MsgBox.alert(this, "Vui lòng chọn giới tính");
            return false;
        }
        
        Icon a = new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Images/user.png"));
        
        if (lbl_Img.getIcon() == a) {
            MsgBox.alert(this, "Lỗi hình ảnh");
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Add;
    private javax.swing.JLabel btn_Clear;
    private javax.swing.JLabel btn_Delete;
    private javax.swing.JLabel btn_First;
    private javax.swing.JLabel btn_Last;
    private javax.swing.JLabel btn_Next;
    private javax.swing.JLabel btn_Prev;
    private javax.swing.JLabel btn_Update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbb_Degree;
    private javax.swing.JComboBox<String> cbb_Department;
    private javax.swing.JComboBox<String> cbb_Duty;
    private com.Nhom5.datechooser.DateChooser dateChooser1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private com.Nhom5.Swing.BoderRadius lbl_Avatar;
    private javax.swing.JLabel lbl_DutyOfUser;
    private com.Nhom5.Swing.BoderRadius lbl_Img;
    private javax.swing.JLabel lbl_NameOfUser;
    private javax.swing.JLabel lbl_VND;
    private javax.swing.JPanel pn_Contact;
    private javax.swing.JPanel pn_Find;
    private com.Nhom5.Components.pnGradientColor pn_Table;
    private javax.swing.JPanel pn_infoEmployee;
    private javax.swing.JRadioButton rdo_Famale;
    private javax.swing.JRadioButton rdo_Male;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JTextField txt_Birthday;
    private javax.swing.JTextField txt_CZC;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_PhoneNumber;
    private javax.swing.JTextField txt_SalaryBasic;
    // End of variables declaration//GEN-END:variables

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon myImage = new ImageIcon(ImagePath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lbl_Img.getWidth(), lbl_Img.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    public void clearForm() {
        txt_Name.setText("Họ và tên");
        txt_Birthday.setText("Ngày sinh");
        txt_CZC.setText("");
        rdo_Male.setSelected(false);
        rdo_Male.setSelected(false);
        txt_Id.setText("");
        txt_PhoneNumber.setText("");
        txt_Address.setText("");
        txt_SalaryBasic.setText("");
        lbl_Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Nhom5/Images/user.png"))); // NOI18N);
        txt_Name.requestFocus();
//        if (nv.getHinh() != null) {
//            lblHinh.setIcon(XImage.read(nv.getHinh()));
//        }
//        txtdiaChi.setText(nv.getDiaChi());

    }

    public void fillCbbDepartment() {
        DepartmentDAO dao = new DepartmentDAO();
        List<Department> list = new ArrayList<Department>();
        list = dao.selectAll();
        for (Department x : list) {
            department.addElement(x.getNameDepartment());
        }
        cbb_Department.setModel(department);
    }

    public void fillCbbDuty() {
        DutyDAO dao = new DutyDAO();
        List<Duty> list = new ArrayList<Duty>();
        list = dao.selectAll();
        for (Duty x : list) {
            duty.addElement(x.getNameDuty());
        }
        cbb_Duty.setModel(duty);
    }

    public void fillCbbDegree() {
        DegreeDAO dao = new DegreeDAO();
        List<Degree> list = new ArrayList<Degree>();
        list = dao.selectAll();
        for (Degree x : list) {
            degree.addElement(x.getNameDegree());
        }
        cbb_Degree.setModel(degree);
    }

    void selectImage() {
        int x = fileChooser.showDialog(this, "Open");
        if (x == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (XImage.save(file)) {
                // Hiển thị hình lên form
                lbl_Img.setIcon(XImage.read(file.getName()));
                lbl_Img.setToolTipText(file.getName());
            }
        }
    }

    public void checkLimitDate() {
        dateChooser1.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());

                int hour, second, minute;
                int day, month, year;
                String timeStr, yearStr;
                Calendar c = Calendar.getInstance();
                hour = c.get(Calendar.HOUR_OF_DAY);
                if (hour > 12) {
                    hour = hour - 12;
                }
                minute = c.get(Calendar.MINUTE);
                second = c.get(Calendar.SECOND);
                year = c.get(Calendar.YEAR);
                month = c.get(Calendar.MONTH);
                day = c.get(Calendar.DAY_OF_MONTH);
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
                SimpleDateFormat df = new SimpleDateFormat("MM-dd-yyy");
                Date dat = c.getTime();
                timeStr = sdf.format(dat);
                yearStr = df.format(dat);

                if (date.getYear() > year) {
                    MsgBox.alert(PnEmployee.this, "Ngày sinh không hợp lệ");
                    dateChooser1.showPopup();
                    txt_Birthday.setText("");
                } else if (date.getYear() == year && date.getMonth() > (month + 1)) {
                    MsgBox.alert(PnEmployee.this, "Ngày sinh không hợp lệ");
                    dateChooser1.showPopup();
                    txt_Birthday.setText("");
                } else if (date.getYear() == year && date.getMonth() == (month + 1) && date.getDay() > day) {
                    MsgBox.alert(PnEmployee.this, "Ngày sinh không hợp lệ");
                    dateChooser1.showPopup();
                    txt_Birthday.setText("");
                }
            }
        });
    }
}
